TRACKS = {
    "Monaco": {
        "laps": 78,
        "overtake_difficulty": "Hard",
        "pit_lane_loss": 26.0,
        "tyre_wear_multiplier": 0.6,
        "sc_probability": 0.35,
        "dnf_probability": 0.04,
        "drs_zones": 1,
        "description": "Street circuit. Impossible to overtake. Strategy is everything.",
        "best_strategy": "Qualify well. One stop. Defend hard.",
        "flag": "🇲🇨"
    },
    "Monza": {
        "laps": 53,
        "overtake_difficulty": "Easy",
        "pit_lane_loss": 21.0,
        "tyre_wear_multiplier": 0.7,
        "sc_probability": 0.15,
        "dnf_probability": 0.02,
        "drs_zones": 2,
        "description": "Temple of speed. Low downforce. Easy overtaking on long straights.",
        "best_strategy": "Two stop soft-soft. Undercut aggressively.",
        "flag": "🇮🇹"
    },
    "Silverstone": {
        "laps": 52,
        "overtake_difficulty": "Medium",
        "pit_lane_loss": 22.5,
        "tyre_wear_multiplier": 1.3,
        "sc_probability": 0.20,
        "dnf_probability": 0.02,
        "drs_zones": 2,
        "description": "High speed corners destroy tyres fast. Degradation is the story.",
        "best_strategy": "Two stop. Manage the rears through Copse and Maggots.",
        "flag": "🇬🇧"
    },
    "Spa": {
        "laps": 44,
        "overtake_difficulty": "Medium",
        "pit_lane_loss": 23.0,
        "tyre_wear_multiplier": 0.9,
        "sc_probability": 0.30,
        "dnf_probability": 0.03,
        "drs_zones": 2,
        "description": "Weather changes everything here. Rain likely. SC common.",
        "best_strategy": "Watch the weather. Be ready to react.",
        "flag": "🇧🇪"
    },
    "Suzuka": {
        "laps": 53,
        "overtake_difficulty": "Hard",
        "pit_lane_loss": 24.0,
        "tyre_wear_multiplier": 1.1,
        "sc_probability": 0.20,
        "dnf_probability": 0.03,
        "drs_zones": 1,
        "description": "Technical circuit. High tyre stress through S curves.",
        "best_strategy": "One stop medium-hard. Overcut works well here.",
        "flag": "🇯🇵"
    },
    "Bahrain": {
        "laps": 57,
        "overtake_difficulty": "Medium",
        "pit_lane_loss": 22.0,
        "tyre_wear_multiplier": 1.2,
        "sc_probability": 0.15,
        "dnf_probability": 0.02,
        "drs_zones": 3,
        "description": "High tyre degradation. Three DRS zones. Overtaking possible.",
        "best_strategy": "Two stop. Undercut from lap 14-16.",
        "flag": "🇧🇭"
    },
    "Abu Dhabi": {
        "laps": 58,
        "overtake_difficulty": "Medium",
        "pit_lane_loss": 22.0,
        "tyre_wear_multiplier": 0.8,
        "sc_probability": 0.12,
        "dnf_probability": 0.02,
        "drs_zones": 2,
        "description": "Season finale track. Low wear. Two stop often fastest.",
        "best_strategy": "Soft start. Pit early. Two stop.",
        "flag": "🇦🇪"
    },
    "Singapore": {
        "laps": 62,
        "overtake_difficulty": "Hard",
        "pit_lane_loss": 27.0,
        "tyre_wear_multiplier": 0.7,
        "sc_probability": 0.40,
        "dnf_probability": 0.04,
        "drs_zones": 1,
        "description": "Street circuit. Night race. SC almost guaranteed. Pit under SC.",
        "best_strategy": "Wait for SC. Free pit stop. Track position everything.",
        "flag": "🇸🇬"
    },
    "Interlagos": {
        "laps": 71,
        "overtake_difficulty": "Easy",
        "pit_lane_loss": 21.5,
        "tyre_wear_multiplier": 1.0,
        "sc_probability": 0.25,
        "dnf_probability": 0.03,
        "drs_zones": 2,
        "description": "Rain likely. Short lap. Overtaking easy. Chaotic races common.",
        "best_strategy": "Be flexible. Weather changes strategy completely.",
        "flag": "🇧🇷"
    },
    "Melbourne": {
        "laps": 58,
        "overtake_difficulty": "Medium",
        "pit_lane_loss": 23.5,
        "tyre_wear_multiplier": 0.8,
        "sc_probability": 0.22,
        "dnf_probability": 0.03,
        "drs_zones": 3,
        "description": "Season opener. Low tyre wear. One stop usually viable.",
        "best_strategy": "One stop medium-hard. React to SC.",
        "flag": "🇦🇺"
    },
    "Zandvoort": {
        "laps": 72,
        "overtake_difficulty": "Hard",
        "pit_lane_loss": 24.0,
        "tyre_wear_multiplier": 1.4,
        "sc_probability": 0.18,
        "dnf_probability": 0.02,
        "drs_zones": 1,
        "description": "Banking corners destroy tyres. Very hard to overtake.",
        "best_strategy": "Two stop. Get ahead early or stay ahead.",
        "flag": "🇳🇱"
    },
    "Hungaroring": {
        "laps": 70,
        "overtake_difficulty": "Hard",
        "pit_lane_loss": 23.0,
        "tyre_wear_multiplier": 1.0,
        "sc_probability": 0.15,
        "dnf_probability": 0.02,
        "drs_zones": 1,
        "description": "Monaco without the walls. Overtaking near impossible. Qualify first.",
        "best_strategy": "Qualify well. One or two stop. Defend.",
        "flag": "🇭🇺"
    },
    "COTA": {
        "laps": 56,
        "overtake_difficulty": "Medium",
        "pit_lane_loss": 23.0,
        "tyre_wear_multiplier": 1.1,
        "sc_probability": 0.18,
        "dnf_probability": 0.02,
        "drs_zones": 2,
        "description": "High energy track. Bumpy surface adds tyre stress.",
        "best_strategy": "Two stop. Soft start, undercut lap 16-18.",
        "flag": "🇺🇸"
    },
    "Jeddah": {
        "laps": 50,
        "overtake_difficulty": "Medium",
        "pit_lane_loss": 21.0,
        "tyre_wear_multiplier": 0.7,
        "sc_probability": 0.35,
        "dnf_probability": 0.04,
        "drs_zones": 3,
        "description": "Street circuit but fast. Walls close. SC very likely.",
        "best_strategy": "Stay flexible. SC will come. Pit under it.",
        "flag": "🇸🇦"
    },
    "Baku": {
        "laps": 51,
        "overtake_difficulty": "Easy",
        "pit_lane_loss": 22.0,
        "tyre_wear_multiplier": 0.6,
        "sc_probability": 0.40,
        "dnf_probability": 0.05,
        "drs_zones": 2,
        "description": "Longest straight in F1. Chaos guaranteed. SC almost certain.",
        "best_strategy": "Low wear means one stop viable. But SC will shake things up.",
        "flag": "🇦🇿"
    },
    "Miami": {
        "laps": 57,
        "overtake_difficulty": "Medium",
        "pit_lane_loss": 22.5,
        "tyre_wear_multiplier": 0.9,
        "sc_probability": 0.20,
        "dnf_probability": 0.02,
        "drs_zones": 3,
        "description": "Newer circuit. High degradation on the surface. Three DRS zones.",
        "best_strategy": "Two stop. Undercut works well.",
        "flag": "🇺🇸"
    },
    "Las Vegas": {
        "laps": 50,
        "overtake_difficulty": "Easy",
        "pit_lane_loss": 21.0,
        "tyre_wear_multiplier": 0.6,
        "sc_probability": 0.25,
        "dnf_probability": 0.03,
        "drs_zones": 2,
        "description": "Night race on the strip. Cold track temps. Tyre warm up tricky.",
        "best_strategy": "One stop. Hard tyre goes a long way in cold conditions.",
        "flag": "🇺🇸"
    },
    "Shanghai": {
        "laps": 56,
        "overtake_difficulty": "Medium",
        "pit_lane_loss": 23.5,
        "tyre_wear_multiplier": 1.0,
        "sc_probability": 0.18,
        "dnf_probability": 0.02,
        "drs_zones": 2,
        "description": "Long back straight. Two stop standard here.",
        "best_strategy": "Two stop soft-medium-medium.",
        "flag": "🇨🇳"
    },
    "Barcelona": {
        "laps": 66,
        "overtake_difficulty": "Hard",
        "pit_lane_loss": 23.0,
        "tyre_wear_multiplier": 1.3,
        "sc_probability": 0.12,
        "dnf_probability": 0.02,
        "drs_zones": 2,
        "description": "High downforce, high wear. Classic two stop circuit.",
        "best_strategy": "Two stop. Manage the fronts through Turn 3.",
        "flag": "🇪🇸"
    },
    "Imola": {
        "laps": 63,
        "overtake_difficulty": "Hard",
        "pit_lane_loss": 24.5,
        "tyre_wear_multiplier": 0.9,
        "sc_probability": 0.22,
        "dnf_probability": 0.03,
        "drs_zones": 1,
        "description": "Old school circuit. Narrow. Hard to overtake. Track position key.",
        "best_strategy": "One stop. Get ahead at the start and hold.",
        "flag": "🇮🇹"
    },
    "Montreal": {
        "laps": 70,
        "overtake_difficulty": "Easy",
        "pit_lane_loss": 22.0,
        "tyre_wear_multiplier": 0.7,
        "sc_probability": 0.30,
        "dnf_probability": 0.03,
        "drs_zones": 2,
        "description": "Stop and go circuit. Low wear but SC disrupts everything.",
        "best_strategy": "One stop but be ready to react to SC.",
        "flag": "🇨🇦"
    },
    "Lusail": {
        "laps": 57,
        "overtake_difficulty": "Medium",
        "pit_lane_loss": 22.0,
        "tyre_wear_multiplier": 1.5,
        "sc_probability": 0.15,
        "dnf_probability": 0.02,
        "drs_zones": 2,
        "description": "Highest tyre wear on the calendar. Two stop minimum.",
        "best_strategy": "Two stop mandatory. Manage carefully between stints.",
        "flag": "🇶🇦"
    },
    "Mexico City": {
        "laps": 71,
        "overtake_difficulty": "Medium",
        "pit_lane_loss": 23.0,
        "tyre_wear_multiplier": 0.6,
        "sc_probability": 0.18,
        "dnf_probability": 0.02,
        "drs_zones": 3,
        "description": "High altitude reduces downforce and tyre wear dramatically.",
        "best_strategy": "One stop viable. Hard tyre lasts forever here.",
        "flag": "🇲🇽"
    },
    "Yas Marina": {
        "laps": 58,
        "overtake_difficulty": "Medium",
        "pit_lane_loss": 22.0,
        "tyre_wear_multiplier": 0.8,
        "sc_probability": 0.12,
        "dnf_probability": 0.02,
        "drs_zones": 2,
        "description": "Revised layout improved overtaking. Clean races usually.",
        "best_strategy": "Two stop soft start. Undercut lap 18-20.",
        "flag": "🇦🇪"
    }
}

TRACK_NAMES = sorted(TRACKS.keys())